[package]
name = "executor-common"
description = "Common definitions for all platforms' executors"

version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
